# Site settings
title:          "Jinjoo's Devlog"
description:    "JInjoo park's devlopment blog"
url:            "https://perlpark.github.io"

# Author
author:
  name:         Jinjoo
  introduce:    ì›¹ì—ì´ì „ì‹œì—ì„œ ê·¼ë¬´ì¤‘ì¸ ê¸°íšì. ğŸŒ³ğŸŒ»ğŸ½ğŸğŸ¥ŸğŸµğŸ‘©â€ğŸ’»â™»ï¸ ê´€ì‹¬ìˆëŠ” ê²ƒì´ ë„ˆë¬´ ë§ì•„ í˜ë“¦.ğŸ™„
  url:          http://jinjoo.me
  email:        jinjoopark5@gmail.com
  facebook:     https://www.facebook.com/profile.php?id=100009151025883
  twitter:      
  instagram:    
  naverblog:    http://blog.jinjoo.me

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme